SEGMENTS = [
    # (slide, narration)
    ("s01", "Neuron Wire. Infrastructure for decentralized AI. A Rust framework that lets any reachable device join a collaborative learning network — no central coordinator, no server to provision, no private data leaving the device. This is the validated research prototype, version 0.3.1, with three hundred and forty-two tests passing on Linux CI, and every result pinned to a single verified commit."),
    ("s02", "The problem. Centralized AI concentrates power, trust, and cost in one provider. Training data must leave your device, and edge hardware is locked out of collective learning. Neuron Wire answers with peer-to-peer gradient exchange: nodes discover each other through a latency-weighted Kademlia DHT, and gradients — never raw data — travel between peers over reliable UDP."),
    ("s03", "The architecture is one auditable Rust codebase. A latency-weighted Kademlia DHT with O of log N convergence. A custom reliable UDP transport with three reliability tiers and gradient aging, sustaining roughly four hundred kilohertz to one megahertz ticks on commodity hardware — with zero async runtime dependency. Ed25519 packet authentication with optional encryption. Hebbian STDP learning with neurogenesis and apoptosis. And a deterministic paper-mode simulator for reproducible experiments."),
    ("s04", "The evidence is reproduced, not asserted. Three hundred and forty-two tests pass on Linux CI with zero warnings. The E1 through E9 experiment matrix covers node churn, partitions, malicious routing, and gradient decay. One hundred thousand nodes converge fully in forty-three seconds in the deterministic simulator. Twenty-five real processes converge over localhost UDP. The neurogenesis effect on bandwidth is a robust twenty-three to twenty-five percent. And seven real bugs caught by the pipeline are documented honestly as negative results."),
    ("s05", "Distributed learning works end to end. Node A fires an activation frame over real UDP. Node B decodes it, and Hebbian plasticity raises the synapse weight from zero point five to above zero point six, then sends the learning signal back to A. Same seed, same weight change — deterministic. This test caught a real production bug: the Adam optimiser produced NaN on its first tick. It is fixed, with regression tests."),
    ("s06", "The funding request is twenty thousand dollars. It buys a twenty-node, three-region pilot sustained for seven days with a public dashboard. An external security audit of the cryptographic and transport layers. Independent reproduction, plus comparison against FedAvg and decentralized SGD. And publication: reproducible datasets and a peer-reviewed paper, including negative findings. Ten and five thousand dollar alternative packages exist."),
    ("s07", "The roadmap. Milestones one through four are complete: green CI, reproducible hundred-node simulation, local twenty-five-process test, and network emulation benchmarks. Milestone five is the funded twenty-node pilot. Milestone six is publication and the external audit. The next engineering milestone is a secure distributed-learning end-to-end test — and grant submission. Not more features."),
    ("s08", "Every number in this demonstration is one command away. Clone the repository, run cargo test — three hundred and forty-two pass. The evidence report links each result to its commit-pinned CI and evidence runs. Neuron Wire: validated research prototype, ready for the real Internet. The grant package is in the docs directory. Thank you."),
]
